In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [8]:
df= pd.read_excel(r'C:\Users\ABC\Desktop\Python\Data_Science\spine_project/spine.xlsx')

In [9]:
df.tail(10)

PG_Count  GSM  Binding   Paper      Spine
11990      1191   75  Hardback  crème  65.867375
11991      1192   75  Hardback  crème  65.921000
11992      1193   75  Hardback  crème  65.974625
11993      1194   75  Hardback  crème  66.028250
11994      1195   75  Hardback  crème  66.081875
11995      1196   75  Hardback  crème  66.135500
11996      1197   75  Hardback  crème  66.189125
11997      1198   75  Hardback  crème  66.242750
11998      1199   75  Hardback  crème  66.296375
11999      1200   75  Hardback  crème  66.350000

In [10]:
df1= df.to_csv("spine_data.csv", index=False)

In [11]:
df= pd.read_csv("spine_data.csv")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   PG_Count  12000 non-null  int64  
 1   GSM       12000 non-null  int64  
 2   Binding   12000 non-null  object 
 3   Paper     12000 non-null  object 
 4   Spine     12000 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 468.9+ KB


In [13]:
df.columns

Index(['PG_Count', 'GSM', 'Binding ', 'Paper', 'Spine'], dtype='object')

In [14]:
df["Binding "].value_counts()

paperback    6000
Hardback     6000
Name: Binding , dtype: int64

In [15]:
df["Binding "].replace({"paperback":0, "Hardback":1}, inplace=True)

In [16]:
df["Binding "].value_counts()

0    6000
1    6000
Name: Binding , dtype: int64

In [19]:
df["Paper"].value_counts()

creme          4800
White          4800
Coated_matt    2400
Name: Paper, dtype: int64

In [18]:
df["Paper"].replace({"crème":"creme"}, inplace=True)

In [20]:
df = pd.get_dummies(df, columns=['Paper'])
df

PG_Count  GSM  Binding       Spine  Paper_Coated_matt  Paper_White  \
0             1   55         0   0.655000                  0            0   
1             2   55         0   0.710000                  0            0   
2             3   55         0   0.765000                  0            0   
3             4   55         0   0.820000                  0            0   
4             5   55         0   0.875000                  0            0   
...         ...  ...       ...        ...                ...          ...   
11995      1196   75         1  66.135500                  0            0   
11996      1197   75         1  66.189125                  0            0   
11997      1198   75         1  66.242750                  0            0   
11998      1199   75         1  66.296375                  0            0   
11999      1200   75         1  66.350000                  0            0   

       Paper_creme  
0                1  
1                1  
2                1  
3                1  
4                1  
...            ...  
11995            1  
11996            1  
11997            1  
11998            1  
11999            1  

[12000 rows x 7 columns]

In [21]:
df.head()

PG_Count  GSM  Binding   Spine  Paper_Coated_matt  Paper_White  Paper_creme
0         1   55         0  0.655                  0            0            1
1         2   55         0  0.710                  0            0            1
2         3   55         0  0.765                  0            0            1
3         4   55         0  0.820                  0            0            1
4         5   55         0  0.875                  0            0            1

In [22]:
x= df.drop('Spine', axis=1)
y= df['Spine']
y.shape, x.shape

((12000,), (12000, 6))

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state= 12)
x_train.shape,y_train.shape,y_test.shape

((9600, 6), (9600,), (2400,))

In [24]:
model= LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

# model evealution

In [25]:
def model_eval(model, x, y):
    y_pred = model.predict(x)
    mse= mean_squared_error(y,y_pred)
    print(f'mean squared error= {mse}')
    mae= mean_absolute_error(y,y_pred)
    print(f'mean absolute error= {mae}')
    r2= r2_score(y,y_pred)
    print(f'r2 score= {r2}')
    
    return mse, mae, r2
model_eval(model, x_train,y_train)

mean squared error= 8.287052902044431
mean absolute error= 2.226350137982666
r2 score= 0.9739416434765485


(8.287052902044431, 2.226350137982666, 0.9739416434765485)

# testing model evaluation

In [26]:
model_eval(model, x_test,y_test)

mean squared error= 8.139946236656337
mean absolute error= 2.2236975861055517
r2 score= 0.9743788441281868


(8.139946236656337, 2.2236975861055517, 0.9743788441281868)

In [27]:
df.columns

Index(['PG_Count', 'GSM', 'Binding ', 'Spine', 'Paper_Coated_matt',
       'Paper_White', 'Paper_creme'],
      dtype='object')

In [28]:
PG_Count= 120
GSM = 75
Binding = 0
Paper_Coated_matt= 0
Paper_White = 1
Paper_crème = 0
data = [PG_Count, GSM, Binding , Paper_Coated_matt,
       Paper_White, Paper_crème]

y_pred = model.predict([data])
y_pred

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.96137156])

In [29]:
model1 = KNeighborsRegressor()
model1.fit(x_train,y_train)

KNeighborsRegressor()

In [30]:
print ("Test model evaluation")
model_eval(model1, x_test,y_test)
print ('#' * 30)
print ("Train model evaluation")
model_eval(model, x_train,y_train)

Test model evaluation
mean squared error= 0.5860572801049185
mean absolute error= 0.7116938941666668
r2 score= 0.9981553361058135
##############################
Train model evaluation
mean squared error= 8.287052902044431
mean absolute error= 2.226350137982666
r2 score= 0.9739416434765485


(8.287052902044431, 2.226350137982666, 0.9739416434765485)

In [31]:
PG_Count= 1100
GSM = 75
Binding = 0
Paper_Coated_matt= 0
Paper_White = 0
Paper_crème = 1
data = [PG_Count, GSM, Binding , Paper_Coated_matt,
       Paper_White, Paper_crème]

y_pred = model1.predict([data])
y_pred

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([60.4275])

In [32]:
model3= DecisionTreeRegressor()
model3.fit(x_train,y_train)

DecisionTreeRegressor()

In [33]:
print ("Test model evaluation")
model_eval(model3, x_test,y_test)
print ('#' * 30)
print ("Train model evaluation")
model_eval(model3, x_train,y_train)

Test model evaluation
mean squared error= 0.0031945743802708386
mean absolute error= 0.0537772291666667
r2 score= 0.9999899448121939
##############################
Train model evaluation
mean squared error= 0.0
mean absolute error= 0.0
r2 score= 1.0


(0.0, 0.0, 1.0)

In [34]:
PG_Count= 1100
GSM = 75
Binding = 1
Paper_Coated_matt= 1
Paper_White = 0
Paper_crème = 0
data = [PG_Count, GSM, Binding , Paper_Coated_matt,
       Paper_White, Paper_crème]

y_pred = model3.predict([data])
y_pred

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([58.925])

In [35]:
import pickle

with open('model.pkl','wb') as file: 
    pickle.dump(model3,file)

In [36]:
x.columns.tolist()

['PG_Count',
 'GSM',
 'Binding ',
 'Paper_Coated_matt',
 'Paper_White',
 'Paper_creme']

In [37]:
import json
project_data = {"column_names":x.columns.tolist(),
               "Binding ":{'paperback': 0, 'Hardback': 1}
               }

with open('project_data.json','w') as file:
    json.dump(project_data,file)

In [73]:
with open('project_data.json','r') as file:
    project_data = json.load(file)

PG_Count= 1100
GSM = 75
Binding = 'paperback'

user_data = np.zeros(len(project_data['column_names']))
user_data[0] = PG_Count
user_data[1] = GSM
user_data[2] = project_data['Binding '][Binding]
   
search_paper = 'Paper_'+'creme'
index = np.where(np.array(project_data['column_names']) == search_paper)[0][0]
user_data[index] = 1
index

5

In [64]:
project_data['Binding ']['Hardback']

1